import type { Category, Level } from "../types";

type Catalog = Readonly<Record<Category, Readonly<Record<Level, readonly string[]>>>>;

export const ROASTS = {
  general: {
    mild: [
      "You bring strong 'works on my machine' energy to problems that do not involve a machine.",
      "Your plan has excellent documentation for something nobody intends to do.",
      "You have the confidence of a green checkmark and the context of an empty README.",
      "That idea shipped with all the urgency of a calendar invite titled 'quick sync.'",
      "You have successfully optimized the part nobody was waiting on.",
      "Your status update answered every question except what is happening.",
      "You brought enterprise confidence to a problem with hobby-project evidence.",
      "Your estimate has already entered the realm of historical fiction.",
      "You have the rare ability to make a simple task arrive with a steering committee.",
      "Your confidence entered the room ten minutes before the evidence.",
      "You keep saying 'low effort' like the task has not already opened a Jira epic.",
      "Your plan is technically actionable if time, gravity, and three dependencies cooperate.",
    ],
    spicy: [
      "Your decision-making process is basically undefined behavior with a LinkedIn profile.",
      "You are not blocked. You are load-bearing technical debt with calendar access.",
      "Your roadmap has more fiction than the dependency graph you swear is under control.",
      "You turned a five-minute problem into a cross-functional learning opportunity.",
      "Your strategy is a race condition between confidence and consequences.",
      "You are operating at senior velocity with intern-grade blast-radius awareness.",
      "Your process has so many guardrails it forgot to build a road.",
      "You keep calling it momentum because uncontrolled descent sounds bad in the quarterly review.",
      "Your execution strategy is just panic wearing a roadmap lanyard.",
      "You have turned avoiding a decision into a reusable organizational capability.",
      "Your priorities are arranged by whichever fire has the best calendar visibility.",
      "You keep shipping context-free certainty like it is a premium feature.",
    ],
    dark: [
      "Your project has entered the hospice phase where everyone calls outages 'learning opportunities.'",
      "Your architecture review has the energy of a coroner's report: everyone knows what died, nobody wants the timestamp.",
      "The good news is your system has achieved immortality. Nobody understands it well enough to kill it.",
      "Your backlog is not a plan. It is a mass grave with Jira permissions.",
      "Your initiative has been declared technically alive because finance has not found the body.",
      "The project is now in organ-donor status; every surviving service has taken a dependency.",
      "Your postmortem is going to need a family tree.",
      "The roadmap ends in a fog bank labeled organizational learning.",
      "Your project is not failing; it is being slowly converted into evidence.",
      "The initiative still has executive sponsorship, which is how you know the body has not been identified.",
      "Your delivery plan is a candlelight vigil with milestones.",
      "The project status is green because nobody authorized the dashboard to pronounce it dead.",
    ],
  },
  code: {
    mild: [
      "That function has more responsibilities than the person who approved it.",
      "Your abstraction is doing a fantastic job hiding the part where nothing is actually simpler.",
      "The code is self-documenting in the same way a crime scene is self-documenting.",
      "You named the variable 'data' and somehow made the debugger feel judgmental.",
      "That class has one job, plus seventeen hobbies.",
      "Your naming convention appears to be based on witness protection.",
      "The compiler accepted it, which is not the endorsement you think it is.",
      "You extracted a helper and somehow increased the emotional complexity.",
      "Your function reads like three ideas sharing one trench coat.",
      "The variable names are concise in the same way ransom notes are concise.",
      "You wrote a generic so flexible it no longer remembers what problem it solves.",
      "This interface is less a contract and more a polite rumor.",
    ],
    spicy: [
      "Your codebase is what happens when copy-paste earns merge rights.",
      "That helper function has grown into a small government with no term limits.",
      "You did not remove complexity. You put it behind an interface and changed its phone number.",
      "The type system filed a missing-person report three commits ago.",
      "Every abstraction in this file is hiding from a different mistake.",
      "Your code has layers like an onion if the onion was maintained by six vendors.",
      "This module has enough side effects to qualify as weather.",
      "You solved the circular dependency by making the whole codebase emotionally codependent.",
      "Your abstraction has abstracted away the last person who understood the feature.",
      "This file has enough indirection to qualify as witness relocation.",
      "You refactored the duplication into one centralized source of confusion.",
      "The dependency injection container is now basically a haunted vending machine.",
    ],
    dark: [
      "This code is a digital crime scene and git blame is the autopsy report.",
      "Your function has been dead for six releases. Production keeps moving the body.",
      "This repository does not need refactoring. It needs witnesses and a sealed evidence bag.",
      "Your code review is less about correctness now and more about establishing time of death.",
      "The garbage collector keeps circling this module out of professional concern.",
      "This function should be read its rights before the next release.",
      "The dead code is not dead. It is haunting the branch predictor.",
      "Your repository has reached the forensic phase where comments count as dental records.",
      "This module has been declared unmaintainable pending identification of the remains.",
      "Your call stack has become a staircase in an abandoned hospital.",
      "The codebase keeps compiling because apparently software can operate postmortem.",
      "This function is held together by comments written like final letters home.",
    ],
  },
  debugging: {
    mild: [
      "The bug is reproducible, which already makes it more dependable than the feature.",
      "Your debugger has seen things no logging framework should have to remember.",
      "You fixed the symptom so cleanly the root cause almost feels respected.",
      "The stack trace is trying harder to communicate than the original ticket.",
      "The bug only happens in production because it respects ceremony.",
      "You added logging and the bug immediately requested legal counsel.",
      "The reproduction steps are now longer than the feature.",
      "Your breakpoint placement suggests you have moved from diagnosis to divination.",
      "You found a new symptom, which is technically progress if we lower the lighting.",
      "The bug report has more plot twists than the feature specification.",
      "Your debug log is slowly becoming the product documentation.",
      "The breakpoint worked; unfortunately it only stopped your optimism.",
    ],
    spicy: [
      "You are three breakpoints away from discovering the bug was the architecture all along.",
      "The logs are not noisy. They are screaming over each other because nobody designed observability.",
      "Your workaround has survived long enough to become an undocumented product requirement.",
      "At this point the debugger is just live-streaming consequences.",
      "The bug disappears under observation, which is more self-awareness than the service has shown.",
      "You have ruled out everything except the part that is actually broken.",
      "The stack trace is basically a guided tour of previous compromises.",
      "Your debug session has become a documentary about cascading assumptions.",
      "You fixed the race condition by introducing a second race with clearer logging.",
      "The reproduction is now deterministic, which is terrible news for everyone involved.",
      "Every hypothesis has been eliminated except the one nobody wants to put in the incident notes.",
      "The debugger is not helping anymore; it is documenting the collapse.",
    ],
    dark: [
      "The root cause is buried so deep the stack trace needs next-of-kin notification.",
      "You are not debugging anymore. You are performing digital archaeology at an active disaster site.",
      "The incident ended hours ago. The causal chain is still wandering the building looking for an owner.",
      "Your logs read like final transmissions from services that knew nobody was coming.",
      "The core dump is less a diagnostic artifact and more a will.",
      "Every service says it was the last one to see the request alive.",
      "The bug survived three rewrites and is now legally part of the architecture.",
      "You found the root cause. It has roots.",
      "The stack trace has crossed from diagnostic output into missing-person literature.",
      "You traced the request so far back it now has childhood trauma.",
      "The root cause has begun generating its own root causes.",
      "The core dump looks like the system tried to leave a confession before it went down.",
    ],
  },
  deploy: {
    mild: [
      "Bold deployment strategy: change everything and let observability introduce itself.",
      "Your rollback plan appears to be refreshing the dashboard with conviction.",
      "Production noticed your confidence and has begun preparing a lesson.",
      "The deploy passed CI, which is a beautiful way to begin this mystery.",
      "The progress bar reached 100%, which is where the story usually gets interesting.",
      "Your deployment has entered the confidence-building portion of the outage.",
      "The canary is still alive, but it has stopped singing.",
      "You called it a hotfix because the servers were already warm.",
      "The deployment is progressing normally, which is exactly when experienced people become nervous.",
      "Your change window has all the calm energy of a countdown timer nobody started.",
      "The canary passed, but it keeps looking toward the exit.",
      "Rollback is documented right after the section titled 'unlikely scenarios.'",
    ],
    spicy: [
      "You deployed on Friday because apparently weekends are an observability feature.",
      "Your release process is just Russian roulette with semantic versioning.",
      "That deployment had one canary, and somebody already sent flowers.",
      "Your rollback procedure begins with 'remember what we changed,' so this should go well.",
      "Your deployment pipeline has two stages: optimism and incident command.",
      "The change window is open and production is considering its options.",
      "Your release notes should probably include emergency contact information.",
      "You shipped with confidence levels normally reserved for people who have not checked the logs.",
      "Your deployment checklist is mostly ceremonial protection against consequences.",
      "The release pipeline has reached the stage where everyone suddenly remembers the backup policy.",
      "You shipped twelve changes together so root cause could become a team-building exercise.",
      "Production accepted the release the way a floor accepts a falling glass.",
    ],
    dark: [
      "Production did not go down. It achieved a permanent separation from user expectations.",
      "Your deployment strategy has progressed from blue-green to black-armband.",
      "The release window closed. The incident channel is now handling bereavement.",
      "You called it zero-downtime because technically the service stopped having a meaningful concept of time.",
      "The deployment completed successfully. The application did not.",
      "Your rollback is now an archaeological reconstruction.",
      "Production has been pronounced stable because nothing else is moving.",
      "The release train arrived without brakes and somehow gained stakeholders.",
      "The deploy finished so cleanly the outage had time to dress formally.",
      "Production is not responding because it has retained counsel.",
      "The rollback point is now a historical landmark.",
      "Your release artifact entered production and immediately became an incident artifact.",
    ],
  },
  meetings: {
    mild: [
      "This meeting could have been an email, and the email could have been silence.",
      "Excellent sync. We are now aligned on scheduling another sync.",
      "The agenda contains three bullets and somehow none of them survived contact with the meeting.",
      "Nothing says velocity like twelve people watching one person share a browser tab.",
      "We could have resolved this asynchronously, but apparently calendars needed content.",
      "The meeting produced three action items and a powerful sense of deja vu.",
      "You scheduled a follow-up before the current meeting had developed a purpose.",
      "The only thing being synchronized is everyone's regret.",
      "The meeting had a clear objective until somebody joined.",
      "We have successfully converted one unanswered question into four calendar events.",
      "This agenda is less a plan and more a list of places conversation might escape.",
      "The call ended with alignment, which means nobody objected loudly enough.",
    ],
    spicy: [
      "This meeting is distributed denial of service, but for engineering attention spans.",
      "We assembled six senior engineers to discover somebody needed to update a ticket.",
      "The meeting has no owner, no decision, and apparently no natural predator.",
      "We have reached consensus that nobody knows why we are still on this call.",
      "This call is proof that bandwidth can be converted directly into indecision.",
      "We have forty years of combined experience and are using it to pick a time for another meeting.",
      "The parking lot has more actionable items than the agenda.",
      "Someone said 'circle back' and the meeting became self-sustaining.",
      "This meeting is a memory leak with microphones.",
      "We are using enterprise-grade conferencing software to avoid making a two-line decision.",
      "The call has achieved high availability by refusing to end.",
      "Every participant has action items except the person who called the meeting.",
    ],
    dark: [
      "This meeting died twenty minutes ago, but corporate policy requires the body remain on Zoom until the hour.",
      "The agenda is deceased. We are now preserving its remains in meeting notes nobody will read.",
      "This call has become a hostage situation with screen sharing.",
      "By the time this meeting ends, the original problem will qualify as legacy infrastructure.",
      "This meeting has outlived the ticket, the sprint, and several participants' will to speak.",
      "The decision died quietly somewhere between slide fourteen and 'any other thoughts?'",
      "We are now performing CPR on a conversation that should have been buried as a chat message.",
      "The meeting minutes will serve as the official record of when productivity was last seen.",
      "This meeting is being kept alive by calendar infrastructure against its natural wishes.",
      "The decision log is empty because all decisions were lost at the scene.",
      "We entered with one blocker and will leave with a governance model for the blocker.",
      "The call has become an oral history of why the work did not happen.",
    ],
  },
  security: {
    mild: [
      "Your threat model currently lists 'hopefully nobody notices' as a compensating control.",
      "The security boundary is mostly a strongly worded comment.",
      "Your secret-management strategy has excellent autocomplete support.",
      "That input validation has the structural integrity of a checkbox labeled 'sanitize.'",
      "Your allowlist is doing a lot of emotional labor for that parser.",
      "The control is technically preventive if the attacker reads the documentation first.",
      "Your least-privilege model has been generously interpreted.",
      "That security boundary looks suspiciously like a TODO with capitalization.",
      "Your security control is very effective against attackers who honor signage.",
      "The threat model includes the threat, which is more than the implementation can say.",
      "Your permission boundary has the confidence of a locked door painted on a wall.",
      "You added validation at the edge and trust everywhere behind it immediately filed for overtime.",
    ],
    spicy: [
      "Your attack surface has an attack parking lot and overflow seating.",
      "You did not implement least privilege. You implemented trust with extra steps.",
      "Your security review found no issues because apparently nobody invited the adversary.",
      "That token has lived longer than some production services and has considerably more authority.",
      "Your trust boundary is a dotted line around several acts of faith.",
      "You rotated the key but kept the same bad decisions.",
      "The attack path has better documentation than the happy path.",
      "Your defense-in-depth diagram contains three boxes labeled 'probably Cloudflare.'",
      "Your least-privilege policy currently has a luxury suite and valet parking.",
      "The attacker path is shorter than the onboarding guide.",
      "Your security boundary is held together by one middleware function and collective optimism.",
      "You rotated credentials but left the blast radius on auto-renew.",
    ],
    dark: [
      "Your threat model is a memorial to assumptions the attacker already buried.",
      "The blast radius is no longer a radius. It has zoning laws.",
      "Your security controls are technically defense in depth if we count denial as a layer.",
      "The incident response plan begins after compromise, which is convenient because so does the architecture.",
      "The attacker did not bypass the controls; the controls introduced themselves and stepped aside.",
      "Your incident timeline begins with unknown and ends with consult legal.",
      "The credential was so overprivileged it had succession rights.",
      "Your security posture is now a historical reconstruction based on logs recovered from the blast crater.",
      "The incident responder opened the architecture diagram and quietly added next of kin.",
      "Your trust model has become a crime-scene map with arrows.",
      "The compromise was technically contained once there was nothing left outside the containment zone.",
      "Your forensic timeline is just increasingly confident timestamps around a crater.",
    ],
  },
} as const satisfies Catalog;
