import type { Category, Level } from "../types";

type Catalog = Readonly<Record<Category, Readonly<Record<Level, readonly string[]>>>>;

export const ROASTS = {
  general: {
    mild: [
      "You bring strong 'works on my machine' energy to problems that do not involve a machine.",
      "Your plan has excellent documentation for something nobody intends to do.",
      "You have the confidence of a green checkmark and the context of an empty README.",
      "That idea shipped with all the urgency of a calendar invite titled 'quick sync.'",
      "You have successfully optimized the part nobody was waiting on.",
      "Your status update answered every question except what is happening.",
      "You brought enterprise confidence to a problem with hobby-project evidence.",
      "Your estimate has already entered the realm of historical fiction.",
    ],
    spicy: [
      "Your decision-making process is basically undefined behavior with a LinkedIn profile.",
      "You are not blocked. You are load-bearing technical debt with calendar access.",
      "Your roadmap has more fiction than the dependency graph you swear is under control.",
      "You turned a five-minute problem into a cross-functional learning opportunity.",
      "Your strategy is a race condition between confidence and consequences.",
      "You are operating at senior velocity with intern-grade blast-radius awareness.",
      "Your process has so many guardrails it forgot to build a road.",
      "You keep calling it momentum because uncontrolled descent sounds bad in the quarterly review.",
    ],
    dark: [
      "Your project has entered the hospice phase where everyone calls outages 'learning opportunities.'",
      "Your architecture review has the energy of a coroner's report: everyone knows what died, nobody wants the timestamp.",
      "The good news is your system has achieved immortality. Nobody understands it well enough to kill it.",
      "Your backlog is not a plan. It is a mass grave with Jira permissions.",
      "Your initiative has been declared technically alive because finance has not found the body.",
      "The project is now in organ-donor status; every surviving service has taken a dependency.",
      "Your postmortem is going to need a family tree.",
      "The roadmap ends in a fog bank labeled organizational learning.",
    ],
  },
  code: {
    mild: [
      "That function has more responsibilities than the person who approved it.",
      "Your abstraction is doing a fantastic job hiding the part where nothing is actually simpler.",
      "The code is self-documenting in the same way a crime scene is self-documenting.",
      "You named the variable 'data' and somehow made the debugger feel judgmental.",
      "That class has one job, plus seventeen hobbies.",
      "Your naming convention appears to be based on witness protection.",
      "The compiler accepted it, which is not the endorsement you think it is.",
      "You extracted a helper and somehow increased the emotional complexity.",
    ],
    spicy: [
      "Your codebase is what happens when copy-paste earns merge rights.",
      "That helper function has grown into a small government with no term limits.",
      "You did not remove complexity. You put it behind an interface and changed its phone number.",
      "The type system filed a missing-person report three commits ago.",
      "Every abstraction in this file is hiding from a different mistake.",
      "Your code has layers like an onion if the onion was maintained by six vendors.",
      "This module has enough side effects to qualify as weather.",
      "You solved the circular dependency by making the whole codebase emotionally codependent.",
    ],
    dark: [
      "This code is a digital crime scene and git blame is the autopsy report.",
      "Your function has been dead for six releases. Production keeps moving the body.",
      "This repository does not need refactoring. It needs witnesses and a sealed evidence bag.",
      "Your code review is less about correctness now and more about establishing time of death.",
      "The garbage collector keeps circling this module out of professional concern.",
      "This function should be read its rights before the next release.",
      "The dead code is not dead. It is haunting the branch predictor.",
      "Your repository has reached the forensic phase where comments count as dental records.",
    ],
  },
  debugging: {
    mild: [
      "The bug is reproducible, which already makes it more dependable than the feature.",
      "Your debugger has seen things no logging framework should have to remember.",
      "You fixed the symptom so cleanly the root cause almost feels respected.",
      "The stack trace is trying harder to communicate than the original ticket.",
      "The bug only happens in production because it respects ceremony.",
      "You added logging and the bug immediately requested legal counsel.",
      "The reproduction steps are now longer than the feature.",
      "Your breakpoint placement suggests you have moved from diagnosis to divination.",
    ],
    spicy: [
      "You are three breakpoints away from discovering the bug was the architecture all along.",
      "The logs are not noisy. They are screaming over each other because nobody designed observability.",
      "Your workaround has survived long enough to become an undocumented product requirement.",
      "At this point the debugger is just live-streaming consequences.",
      "The bug disappears under observation, which is more self-awareness than the service has shown.",
      "You have ruled out everything except the part that is actually broken.",
      "The stack trace is basically a guided tour of previous compromises.",
      "Your debug session has become a documentary about cascading assumptions.",
    ],
    dark: [
      "The root cause is buried so deep the stack trace needs next-of-kin notification.",
      "You are not debugging anymore. You are performing digital archaeology at an active disaster site.",
      "The incident ended hours ago. The causal chain is still wandering the building looking for an owner.",
      "Your logs read like final transmissions from services that knew nobody was coming.",
      "The core dump is less a diagnostic artifact and more a will.",
      "Every service says it was the last one to see the request alive.",
      "The bug survived three rewrites and is now legally part of the architecture.",
      "You found the root cause. It has roots.",
    ],
  },
  deploy: {
    mild: [
      "Bold deployment strategy: change everything and let observability introduce itself.",
      "Your rollback plan appears to be refreshing the dashboard with conviction.",
      "Production noticed your confidence and has begun preparing a lesson.",
      "The deploy passed CI, which is a beautiful way to begin this mystery.",
      "The progress bar reached 100%, which is where the story usually gets interesting.",
      "Your deployment has entered the confidence-building portion of the outage.",
      "The canary is still alive, but it has stopped singing.",
      "You called it a hotfix because the servers were already warm.",
    ],
    spicy: [
      "You deployed on Friday because apparently weekends are an observability feature.",
      "Your release process is just Russian roulette with semantic versioning.",
      "That deployment had one canary, and somebody already sent flowers.",
      "Your rollback procedure begins with 'remember what we changed,' so this should go well.",
      "Your deployment pipeline has two stages: optimism and incident command.",
      "The change window is open and production is considering its options.",
      "Your release notes should probably include emergency contact information.",
      "You shipped with confidence levels normally reserved for people who have not checked the logs.",
    ],
    dark: [
      "Production did not go down. It achieved a permanent separation from user expectations.",
      "Your deployment strategy has progressed from blue-green to black-armband.",
      "The release window closed. The incident channel is now handling bereavement.",
      "You called it zero-downtime because technically the service stopped having a meaningful concept of time.",
      "The deployment completed successfully. The application did not.",
      "Your rollback is now an archaeological reconstruction.",
      "Production has been pronounced stable because nothing else is moving.",
      "The release train arrived without brakes and somehow gained stakeholders.",
    ],
  },
  meetings: {
    mild: [
      "This meeting could have been an email, and the email could have been silence.",
      "Excellent sync. We are now aligned on scheduling another sync.",
      "The agenda contains three bullets and somehow none of them survived contact with the meeting.",
      "Nothing says velocity like twelve people watching one person share a browser tab.",
      "We could have resolved this asynchronously, but apparently calendars needed content.",
      "The meeting produced three action items and a powerful sense of deja vu.",
      "You scheduled a follow-up before the current meeting had developed a purpose.",
      "The only thing being synchronized is everyone's regret.",
    ],
    spicy: [
      "This meeting is distributed denial of service, but for engineering attention spans.",
      "We assembled six senior engineers to discover somebody needed to update a ticket.",
      "The meeting has no owner, no decision, and apparently no natural predator.",
      "We have reached consensus that nobody knows why we are still on this call.",
      "This call is proof that bandwidth can be converted directly into indecision.",
      "We have forty years of combined experience and are using it to pick a time for another meeting.",
      "The parking lot has more actionable items than the agenda.",
      "Someone said 'circle back' and the meeting became self-sustaining.",
    ],
    dark: [
      "This meeting died twenty minutes ago, but corporate policy requires the body remain on Zoom until the hour.",
      "The agenda is deceased. We are now preserving its remains in meeting notes nobody will read.",
      "This call has become a hostage situation with screen sharing.",
      "By the time this meeting ends, the original problem will qualify as legacy infrastructure.",
      "This meeting has outlived the ticket, the sprint, and several participants' will to speak.",
      "The decision died quietly somewhere between slide fourteen and 'any other thoughts?'",
      "We are now performing CPR on a conversation that should have been buried as a chat message.",
      "The meeting minutes will serve as the official record of when productivity was last seen.",
    ],
  },
  security: {
    mild: [
      "Your threat model currently lists 'hopefully nobody notices' as a compensating control.",
      "The security boundary is mostly a strongly worded comment.",
      "Your secret-management strategy has excellent autocomplete support.",
      "That input validation has the structural integrity of a checkbox labeled 'sanitize.'",
      "Your allowlist is doing a lot of emotional labor for that parser.",
      "The control is technically preventive if the attacker reads the documentation first.",
      "Your least-privilege model has been generously interpreted.",
      "That security boundary looks suspiciously like a TODO with capitalization.",
    ],
    spicy: [
      "Your attack surface has an attack parking lot and overflow seating.",
      "You did not implement least privilege. You implemented trust with extra steps.",
      "Your security review found no issues because apparently nobody invited the adversary.",
      "That token has lived longer than some production services and has considerably more authority.",
      "Your trust boundary is a dotted line around several acts of faith.",
      "You rotated the key but kept the same bad decisions.",
      "The attack path has better documentation than the happy path.",
      "Your defense-in-depth diagram contains three boxes labeled 'probably Cloudflare.'",
    ],
    dark: [
      "Your threat model is a memorial to assumptions the attacker already buried.",
      "The blast radius is no longer a radius. It has zoning laws.",
      "Your security controls are technically defense in depth if we count denial as a layer.",
      "The incident response plan begins after compromise, which is convenient because so does the architecture.",
      "The attacker did not bypass the controls; the controls introduced themselves and stepped aside.",
      "Your incident timeline begins with unknown and ends with consult legal.",
      "The credential was so overprivileged it had succession rights.",
      "Your security posture is now a historical reconstruction based on logs recovered from the blast crater.",
    ],
  },
} as const satisfies Catalog;
